[versions]
bstats = "3.2.1" # https://mvnrepository.com/artifact/org.bstats/bstats-bukkit
configurateYaml = "4.2.0" # https://github.com/SpongePowered/Configurate/releases
commandapi = "11.2.0" # https://central.sonatype.com/artifact/dev.jorel/commandapi-paper-shade
dotenv = "4.0.0" # https://plugins.gradle.org/plugin/co.uzzu.dotenv.gradle
itemregistry = "main-SNAPSHOT" # https://jitpack.io/#qheilmann/itemregistry
jpenilla-run-paper = "3.0.2" # https://plugins.gradle.org/plugin/xyz.jpenilla.run-paper
jspecify = "1.0.0" # https://mvnrepository.com/artifact/org.jspecify/jspecify
junit-bom = "6.1.0" # https://mvnrepository.com/artifact/org.junit/junit-bom
paper-api = "26.2.build.+" # https://repo.papermc.io/ui/packages?name=io.papermc.paper%3Apaper-api&type=packages | Don't forget to update the api version paper-plugin.yml | You can see api-version pattern here https://docs.papermc.io/paper/dev/getting-started/paper-plugins/
paper-run = "26.2" # Server version for jpenilla-run-paper plugin
shadow = "9.4.2" # https://plugins.gradle.org/plugin/com.gradleup.shadow

[libraries]
# Core dependencies
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper-api" }
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }

# API / Plugin dependencies
bstats = { module = "org.bstats:bstats-bukkit", version.ref = "bstats" }
commandapi-shade = { module = "dev.jorel:commandapi-paper-shade", version.ref = "commandapi" }
configurateYaml = { module = "org.spongepowered:configurate-yaml", version.ref = "configurateYaml" }
itemregistry = { module = "com.github.qheilmann:itemregistry", version.ref = "itemregistry" }

# Testing
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit-bom"}
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform = { module = "org.junit.platform:junit-platform-launcher" }

[bundles]
junit = ["junit-jupiter", "junit-platform"]

[plugins]
dotenv = { id = "co.uzzu.dotenv.gradle", version.ref = "dotenv" }
jpenilla-run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "jpenilla-run-paper" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
